//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class komandorEntities : DbContext
    {
        public komandorEntities()
            : base("name=komandorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Акции> Акции { get; set; }
        public virtual DbSet<Акционный_товар> Акционный_товар { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Ликвидация> Ликвидация { get; set; }
        public virtual DbSet<Отделы> Отделы { get; set; }
        public virtual DbSet<Планограмма> Планограмма { get; set; }
        public virtual DbSet<Пол> Пол { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<Скидки> Скидки { get; set; }
        public virtual DbSet<Склад> Склад { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Списания> Списания { get; set; }
        public virtual DbSet<Тип_товара> Тип_товара { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
        public virtual DbSet<Фото_товара> Фото_товара { get; set; }
    }
}
