//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Акционный_товар
    {
        public int ID { get; set; }
        public Nullable<int> Наименование { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<int> Условия_акции { get; set; }
        public Nullable<int> Фото { get; set; }
    
        public virtual Акции Акции { get; set; }
        public virtual Товар Товар { get; set; }
        public virtual Товар Товар1 { get; set; }
    }
}
