//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.Акционный_товар = new HashSet<Акционный_товар>();
            this.Акционный_товар1 = new HashSet<Акционный_товар>();
            this.Ликвидация = new HashSet<Ликвидация>();
            this.Ликвидация1 = new HashSet<Ликвидация>();
            this.Скидки = new HashSet<Скидки>();
            this.Скидки1 = new HashSet<Скидки>();
            this.Скидки2 = new HashSet<Скидки>();
            this.Списания = new HashSet<Списания>();
            this.Списания1 = new HashSet<Списания>();
        }
    
        public int ID { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Тип_товара { get; set; }
        public Nullable<int> Номенклатурный_номер { get; set; }
        public Nullable<decimal> Закупочная_цена { get; set; }
        public Nullable<decimal> Наценка_компании { get; set; }
        public Nullable<decimal> Цена_товара { get; set; }
        public Nullable<int> Поставщик { get; set; }
        public Nullable<int> Склад { get; set; }
        public Nullable<int> Фото { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Акционный_товар> Акционный_товар { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Акционный_товар> Акционный_товар1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ликвидация> Ликвидация { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ликвидация> Ликвидация1 { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Скидки> Скидки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Скидки> Скидки1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Скидки> Скидки2 { get; set; }
        public virtual Склад Склад1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Списания> Списания { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Списания> Списания1 { get; set; }
        public virtual Тип_товара Тип_товара1 { get; set; }
        public virtual Фото_товара Фото_товара { get; set; }
    }
}
