//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _068FBBC2_6343_482B_9F49_2C892F9C0B44 {
            get {
                object obj = ResourceManager.GetObject("_068FBBC2_6343_482B_9F49_2C892F9C0B44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _069CA7C0_91F2_4A40_8B5B_AF283D1B5036 {
            get {
                object obj = ResourceManager.GetObject("_069CA7C0_91F2_4A40_8B5B_AF283D1B5036", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0993A387_60D9_4C60_BC32_19E288E7FAF6 {
            get {
                object obj = ResourceManager.GetObject("_0993A387_60D9_4C60_BC32_19E288E7FAF6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0A6CE3DF_6807_4A89_9992_51817EAACEC8 {
            get {
                object obj = ResourceManager.GetObject("_0A6CE3DF_6807_4A89_9992_51817EAACEC8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0B801D77_A7FD_469B_B90E_4609CC912E4F {
            get {
                object obj = ResourceManager.GetObject("_0B801D77_A7FD_469B_B90E_4609CC912E4F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0C32C4CA_ED51_47C6_91DD_F6CC3AF2BB16 {
            get {
                object obj = ResourceManager.GetObject("_0C32C4CA_ED51_47C6_91DD_F6CC3AF2BB16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _0E614068_8B00_4184_ABD8_8463AE6C09D8 {
            get {
                object obj = ResourceManager.GetObject("_0E614068_8B00_4184_ABD8_8463AE6C09D8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _14A02882_9663_4901_B18F_FB32DE7DA4C0 {
            get {
                object obj = ResourceManager.GetObject("_14A02882_9663_4901_B18F_FB32DE7DA4C0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1554F2BF_F19A_4DD2_9EA9_AA221FD2315E {
            get {
                object obj = ResourceManager.GetObject("_1554F2BF_F19A_4DD2_9EA9_AA221FD2315E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1A235C79_0829_484B_8650_AF8C0BAC92A7 {
            get {
                object obj = ResourceManager.GetObject("_1A235C79_0829_484B_8650_AF8C0BAC92A7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1B6B7091_D3F1_4541_85B1_AF4DC320184F {
            get {
                object obj = ResourceManager.GetObject("_1B6B7091_D3F1_4541_85B1_AF4DC320184F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1E85F462_D51E_44AF_BADF_87CF6B75D229 {
            get {
                object obj = ResourceManager.GetObject("_1E85F462_D51E_44AF_BADF_87CF6B75D229", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _20E0328A_4FCA_41A3_8989_C8F92EA27372 {
            get {
                object obj = ResourceManager.GetObject("_20E0328A_4FCA_41A3_8989_C8F92EA27372", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _28B29791_574D_4E32_9816_1D50AB4850E3 {
            get {
                object obj = ResourceManager.GetObject("_28B29791_574D_4E32_9816_1D50AB4850E3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2AF913AC_FCAA_4EF0_AB43_25755211CE28 {
            get {
                object obj = ResourceManager.GetObject("_2AF913AC_FCAA_4EF0_AB43_25755211CE28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _32D2FC14_688F_4802_BB7B_AD5713F48E5E {
            get {
                object obj = ResourceManager.GetObject("_32D2FC14_688F_4802_BB7B_AD5713F48E5E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3C3D7422_49AC_4A64_8A54_94C34B4F8172 {
            get {
                object obj = ResourceManager.GetObject("_3C3D7422_49AC_4A64_8A54_94C34B4F8172", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3CD75825_D6DE_4039_8B42_A1F03089365C {
            get {
                object obj = ResourceManager.GetObject("_3CD75825_D6DE_4039_8B42_A1F03089365C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3ECDA7E7_DEDB_48BA_A9F8_ED9A6A766688 {
            get {
                object obj = ResourceManager.GetObject("_3ECDA7E7_DEDB_48BA_A9F8_ED9A6A766688", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3F0250C4_299F_45E0_BBCD_765CECB3787F {
            get {
                object obj = ResourceManager.GetObject("_3F0250C4_299F_45E0_BBCD_765CECB3787F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3FB9DE09_450B_4E1F_91FE_3E7A648164DE {
            get {
                object obj = ResourceManager.GetObject("_3FB9DE09_450B_4E1F_91FE_3E7A648164DE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _42F92C1E_CA5C_4571_B9C4_598187190140 {
            get {
                object obj = ResourceManager.GetObject("_42F92C1E_CA5C_4571_B9C4_598187190140", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _42F9A7AB_AE19_4FB7_9C1D_E963817DE6E7 {
            get {
                object obj = ResourceManager.GetObject("_42F9A7AB_AE19_4FB7_9C1D_E963817DE6E7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _45D890CE_E9BF_478F_A4FF_EE0E83BF979A {
            get {
                object obj = ResourceManager.GetObject("_45D890CE_E9BF_478F_A4FF_EE0E83BF979A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _47C1A262_0D3C_42C8_A204_1A7267218CB6 {
            get {
                object obj = ResourceManager.GetObject("_47C1A262_0D3C_42C8_A204_1A7267218CB6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4B3C7AC8_4DEF_497E_96DF_DF80ED78DBF4 {
            get {
                object obj = ResourceManager.GetObject("_4B3C7AC8_4DEF_497E_96DF_DF80ED78DBF4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4B9EBEB9_3C0A_48EF_8528_8C89997FE308 {
            get {
                object obj = ResourceManager.GetObject("_4B9EBEB9_3C0A_48EF_8528_8C89997FE308", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4EC0AFD6_F0AB_48FF_8420_BF61E945197A {
            get {
                object obj = ResourceManager.GetObject("_4EC0AFD6_F0AB_48FF_8420_BF61E945197A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4EC6BFE7_AC17_4156_809C_AD851DA371FE {
            get {
                object obj = ResourceManager.GetObject("_4EC6BFE7_AC17_4156_809C_AD851DA371FE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4F1F44E2_E831_43AA_8F7C_108A93EADB4A {
            get {
                object obj = ResourceManager.GetObject("_4F1F44E2_E831_43AA_8F7C_108A93EADB4A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _52E22442_5BD4_4292_B859_3B72344D844E {
            get {
                object obj = ResourceManager.GetObject("_52E22442_5BD4_4292_B859_3B72344D844E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _53BD1496_CEF1_4B4B_8EAF_7F86FB73BFA0 {
            get {
                object obj = ResourceManager.GetObject("_53BD1496_CEF1_4B4B_8EAF_7F86FB73BFA0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _57DC6950_76DA_4580_B46D_1B8601772D6F {
            get {
                object obj = ResourceManager.GetObject("_57DC6950_76DA_4580_B46D_1B8601772D6F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5D398B02_E840_4446_81F0_08BE4D45EA0E {
            get {
                object obj = ResourceManager.GetObject("_5D398B02_E840_4446_81F0_08BE4D45EA0E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5DE78232_6ABA_48E2_80BD_FBD57BC0AD85 {
            get {
                object obj = ResourceManager.GetObject("_5DE78232_6ABA_48E2_80BD_FBD57BC0AD85", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5F0E7539_61C9_40EC_AB8E_81A1F56E805D {
            get {
                object obj = ResourceManager.GetObject("_5F0E7539_61C9_40EC_AB8E_81A1F56E805D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5F8315D7_030C_4D1E_A659_307B8C7D7258 {
            get {
                object obj = ResourceManager.GetObject("_5F8315D7_030C_4D1E_A659_307B8C7D7258", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5FC5C4C8_5E83_4117_A3A7_6CE0C95D2800 {
            get {
                object obj = ResourceManager.GetObject("_5FC5C4C8_5E83_4117_A3A7_6CE0C95D2800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _60_3CEIho68 {
            get {
                object obj = ResourceManager.GetObject("_60_3CEIho68", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _67EC7B18_0EE5_4921_8C6A_DF3B3FACC9CE {
            get {
                object obj = ResourceManager.GetObject("_67EC7B18_0EE5_4921_8C6A_DF3B3FACC9CE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _6A074BBD_7526_4E01_946E_F4CB5F59C2DC {
            get {
                object obj = ResourceManager.GetObject("_6A074BBD_7526_4E01_946E_F4CB5F59C2DC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _6AE4733D_C50D_42D9_A93E_9A8C558B8A5B {
            get {
                object obj = ResourceManager.GetObject("_6AE4733D_C50D_42D9_A93E_9A8C558B8A5B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _725F3C12_9A71_488A_BEE7_01ED30BD832B {
            get {
                object obj = ResourceManager.GetObject("_725F3C12_9A71_488A_BEE7_01ED30BD832B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _72F59E60_F6E2_4D1D_9813_72928F09C095 {
            get {
                object obj = ResourceManager.GetObject("_72F59E60_F6E2_4D1D_9813_72928F09C095", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _75BE6DF2_5C53_46CE_AF29_3E0547530250 {
            get {
                object obj = ResourceManager.GetObject("_75BE6DF2_5C53_46CE_AF29_3E0547530250", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _77E5053D_C814_4284_91DA_EA48F6B5478B {
            get {
                object obj = ResourceManager.GetObject("_77E5053D_C814_4284_91DA_EA48F6B5478B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _78AB8BFF_BC9C_4D08_AA81_BA46742A6063 {
            get {
                object obj = ResourceManager.GetObject("_78AB8BFF_BC9C_4D08_AA81_BA46742A6063", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _80B1F16E_3C9D_40E2_8B7A_3B04FFD8D8DD {
            get {
                object obj = ResourceManager.GetObject("_80B1F16E_3C9D_40E2_8B7A_3B04FFD8D8DD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _855ECBD4_1C33_4D98_9760_8A0D9C20038F {
            get {
                object obj = ResourceManager.GetObject("_855ECBD4_1C33_4D98_9760_8A0D9C20038F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _85B0C07E_7FD2_44DD_ABC7_36C022CAD398 {
            get {
                object obj = ResourceManager.GetObject("_85B0C07E_7FD2_44DD_ABC7_36C022CAD398", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _86B5922A_678F_4468_9B60_961125F9E251 {
            get {
                object obj = ResourceManager.GetObject("_86B5922A_678F_4468_9B60_961125F9E251", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _88A6C3AA_10D2_4220_8626_49D4624D694D {
            get {
                object obj = ResourceManager.GetObject("_88A6C3AA_10D2_4220_8626_49D4624D694D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _88F5F88A_C6DE_4B3C_B0FD_4E0EB51E8AF4 {
            get {
                object obj = ResourceManager.GetObject("_88F5F88A_C6DE_4B3C_B0FD_4E0EB51E8AF4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _89D1AEA0_B2A7_45B7_B27E_6D4EBF62115B {
            get {
                object obj = ResourceManager.GetObject("_89D1AEA0_B2A7_45B7_B27E_6D4EBF62115B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8D45B6F7_7D4A_4218_AA54_3C7FA901AB3E {
            get {
                object obj = ResourceManager.GetObject("_8D45B6F7_7D4A_4218_AA54_3C7FA901AB3E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _90A3354B_FD2D_4CE1_AD26_1054301EF5B1 {
            get {
                object obj = ResourceManager.GetObject("_90A3354B_FD2D_4CE1_AD26_1054301EF5B1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _95A6BC9E_559D_4FDA_9503_4B68A6A08560 {
            get {
                object obj = ResourceManager.GetObject("_95A6BC9E_559D_4FDA_9503_4B68A6A08560", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9E23384F_7937_46DB_870C_D6B192D5540E {
            get {
                object obj = ResourceManager.GetObject("_9E23384F_7937_46DB_870C_D6B192D5540E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9E65DFBE_7F1C_42B4_8AE9_A45F864B0A8A {
            get {
                object obj = ResourceManager.GetObject("_9E65DFBE_7F1C_42B4_8AE9_A45F864B0A8A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9EFD03D5_30A1_4BD6_B235_A37A7C02598D {
            get {
                object obj = ResourceManager.GetObject("_9EFD03D5_30A1_4BD6_B235_A37A7C02598D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _9JpTPt9arMU {
            get {
                object obj = ResourceManager.GetObject("_9JpTPt9arMU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _CRTBcSjG9g {
            get {
                object obj = ResourceManager.GetObject("_CRTBcSjG9g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap F68F9553_0949_4D99_A460_6733C28E15BB {
            get {
                object obj = ResourceManager.GetObject("F68F9553_0949_4D99_A460_6733C28E15BB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gL8hMMqP_pA {
            get {
                object obj = ResourceManager.GetObject("gL8hMMqP_pA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gSng1bGUvJE {
            get {
                object obj = ResourceManager.GetObject("gSng1bGUvJE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap IoUAd5kmLIY {
            get {
                object obj = ResourceManager.GetObject("IoUAd5kmLIY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Jo9jIfYs6Es {
            get {
                object obj = ResourceManager.GetObject("Jo9jIfYs6Es", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
